main:
  push:
    # 导入密钥仓库文件为环境变量
    - imports:
        - https://cnb.cool/tencent/tdesign/tdesign-private/-/blob/main/cnb-envs.yml
      stages:
        - name: sync to github with rebase
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Tencent/tdesign-miniprogram-starter-retail.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
  pull_request:
    - name: commit-lint
      stages:
        - name: commit lint
          image: cnbcool/commitlint
  pull_request.mergeable:
    - name: auto-merge
      stages:
        - name: CR 通过后自动合并
          type: git:auto-merge
          options:
            mergeType: squash
            removeSourceBranch: true
